quarkus:
  http:
    port: 8084
    test-port: 8084

  datasource:
    db-kind: postgresql
    username: postgres
    password: .Napoli121
    jdbc:
      url: jdbc:postgresql://localhost:5435/mosem
      max-size: 8
      min-size: 2

  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
    sql-load-script: import.sql
    envers:
      enabled: true
  arc:
    default-bean-validation: true

  oidc:
    auth-server-url: http://localhost:8080/realms/quarkus-app
    client-id: quarkus-app
    credentials:
      secret: 1lx6BTMLqhS9RkAieWI4zt4oNbU6YU75
    keycloak:
      policy-enforcer:
        enable: true